### ISSUE TITLE
RCA results incorrectly formatting

### ISSUE THREAD

**Issue by alexandersimoes** [tesseract-olap/tesseract-ui#2]
I am trying to calculate the RCA for industries by state and seem to be getting very bizarre results. First there is no `RCA` column and second, the id columns seem to spill over into the wrong cells.

<img width="967" alt="Screen Shot 2019-06-26 at 12 21 20 PM" src="https://user-images.githubusercontent.com/252276/60197415-52a43200-980d-11e9-91b5-609508dc0735.png">

**Comment by frabarz** [comment]
This sometimes happens when there are problems on the schema, is a problem from the server side. I'll check the logs and send the issue to the team.
