### ISSUE TITLE
[tesseract-ui] add support for composable permalinks

### ISSUE THREAD

**Issue by alexandersimoes** [tesseract-olap/tesseract-ui#25]
The idea here is that we will want some way link to a specific vizbuilder selection within tesseract-ui from the CMS profiles. I'm not sure of the exact implementation but one way we discussed solving this was adding a query param to allow a user to give a LL endpoint that could be transformed into a proper tesseract-ui permalink... something like:

domain.com/tesseract-ui/?LL=urlencoded("cube=trade_i_baci_a_92&drilldowns=HS6&measures=Trade+Value")

**Comment by frabarz** [comment]
Implemented in 777f264df32e476016b484c8daac710e6b803971
The parameter is encoded in base64url instead of urlencoding to prevent losing parameters during transmission/handling of permalinks, as some utilities could try to decode `&amp;` in the way and lose the consistency.
