### ISSUE TITLE
Cut state not properly preserved in URL

### ISSUE THREAD

**Issue by greenrhyno** [tesseract-olap/tesseract-ui#31]
Applied cuts are being duplicated on refresh, sometimes contaminating the URL.

Reproduction Steps (in OEC Data Explorer): 

1. Create a basic international trade cube query with a cut on year. You should get a URL something like this: https://dev.oec.world/en/explorer?cube=trade_i_baci_a_17&cuts%5B0%5D=Year%2C2018&drilldowns%5B0%5D=Year&measures%5B0%5D=Trade+Value
2. Refresh the page. There should now be 2 duplicate cuts in the side panel and the URL will now look something like this: https://oec.world/en/explorer?cube=trade_i_baci_a_17&cuts%5B0%5D=Year%2C2018&cuts%5B1%5D=Year%2C2018&drilldowns%5B0%5D=Year&measures%5B0%5D=Trade+Value

![Screen Shot 2021-07-28 at 10 25 23 AM](https://user-images.githubusercontent.com/38231289/127339689-f7fb64c6-46ea-4805-8635-4c6d7d7bd35c.png)

**Comment by alexandersimoes** [comment]
Tested on OEC production site and is not showing up anymore. Will close for now

**Comment by frabarz** [comment]
I published a new version (alpha.15) a few days ago which does some related changes. If it passes, we can close this.
