### ISSUE TITLE
redesign measure/dimension/cut interface

### ISSUE THREAD

**Issue by davelandry** [tesseract-olap/tesseract-ui#40]
- [ ] modify dimension structs
- [ ] list all dimensions with checkbox toggles
- [ ] add "Properties" button to right of dimension name
- [ ] move Menu behavior to list of dimensions
- [ ] move cut popup interface to new filter button next to dimension name
- [ ] Add cut but for measures

**Comment by frabarz** [comment]
I think this was the last mockup we discussed about
![image](https://user-images.githubusercontent.com/11713191/185187449-ae6531cd-ac80-4037-b26e-ceb7dae98948.png)

**Comment by davelandry** [comment]
unless @Anahidena can point us in a different direction? 👀

**Comment by Anahidena** [comment]
yes! yes is a more recent design (for OEC data explorer) but the interface is the same. 👍

![image](https://user-images.githubusercontent.com/80840237/185353141-e660c8ce-08b7-48e0-98a2-439ddc4b63c5.png)

**Comment by frabarz** [comment]
Deprecated in favor of new data-explorer project.
