### ISSUE TITLE
preview query with limit and "load all" button

### ISSUE THREAD

**Issue by davelandry** [tesseract-olap/tesseract-ui#58]
- [x] Default number from props in settings hook
- [x] New boolean query option
- [x] Restricted ui for pagination if preview is enabled
- [x] Translation
- [x] Component button that toggles preview/full
- [x] Change limit value based on new setting (toggle and button)
- [x] Initialize limit value on first setup
- [x] Style callout
- [x] Readme docs

**Comment by palamago** [comment]
Tasks:
- [x] Default number from props in settings hook
- [x] New boolean query option
- [x] Restricted ui for pagination if preview is enabled
- [x] Translation
- [x] Component button that toggles preview/full
- [ ] Change limit value based on new setting (toggle and button)
- [ ] Initialize limit value on first setup
- [ ] Floating button style
- [ ] Readme docs
