### ISSUE TITLE
Number of records doens't work always in the same way

### ISSUE THREAD

**Issue by palamago** [tesseract-olap/tesseract-ui#67]
The Data Explorer in [Next](https://next.oec.world/en/explorer?cube=trade_s_chn_m_hs&cuts%5B0%5D=Partner.Geography.Country%2Cnabrb%2Cnacan%2Cnacri%2Cnadom%2Cnamex%2Cnapan%2Csacol%2Csaecu%2Csaper%2Csaury&cuts%5B1%5D=Time.Year%2C2017%2C2018%2C2019%2C2020%2C2021%2C2022%2C2023&drilldowns%5B0%5D=Time&drilldowns%5B1%5D=Partner.Geography.Country&drilldowns%5B2%5D=Trade+Flow&measures%5B0%5D=Trade+Value) gives me only a fraction of the query -but I can get the correct dataset in [legacy](https://oec.world/en/explorer?cube=trade_s_chn_m_hs&cuts%5B0%5D=Partner.Geography.Country%2Cnabrb%2Cnacan%2Cnacri%2Cnadom%2Cnamex%2Cnapan%2Csacol%2Csaecu%2Csaper%2Csaury&cuts%5B1%5D=Time.Year%2C2017%2C2018%2C2019%2C2020%2C2021%2C2022%2C2023&drilldowns%5B0%5D=Time&drilldowns%5B1%5D=Partner.Geography.Country&drilldowns%5B2%5D=Trade+Flow&measures%5B0%5D=Trade+Value)

known bug, happens in both ui, result limit doesn’t always work correctly

**Comment by frabarz** [comment]
This issue should be resolved with 3ce37ea5ac9531b3c97a0d4186d6ca28c35aa200, but I want to wait until it's deployed before closing it.
